language: node_js
node_js:
  - "0.10"
sudo: false
cache:
  directories:
    - node_modules
    - bower_components
addons:
  postgresql: "9.3"
env:
  - DB=sqlite3 NODE_ENV=testing
  - DB=mysql NODE_ENV=testing-mysql
  - DB=pg NODE_ENV=testing-pg
matrix:
  allow_failures:
    - env: DB=pg NODE_ENV=testing-pg
before_install:
  - git clone git://github.com/n1k0/casperjs.git ~/casperjs
  - cd ~/casperjs
  - git checkout tags/1.1-beta3
  - export PATH=$PATH:`pwd`/bin
  - cd -
  - if [ $DB == "mysql" ]; then mysql -e 'create database ghost_testing'; fi
  - if [ $DB == "pg" ]; then npm install pg; psql -c 'create database ghost_testing;' -U postgres; fi
before_script:
  - phantomjs --version
  - casperjs --version
